packages:
  - apps/*
  - libs/*
  - libs/shared/types

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver
