import { PrismaClient } from '@prisma/client';

interface CreateData {
    name: string;
    youtubeChannelId: string;
    channelUrl: string;
    description: string;
    logoUrl: string | null;
    thumbnailUrl: string | null;
    subscriberCount: number;
    totalVideoCount: number;
    videosInOurDb: number;
    isVerified: boolean;
    isFeatured: boolean;
    qualityScore: number;
}

const allCreators: CreateData[] = [
  {
    name: 'Killa Kev Productions',
    youtubeChannelId: 'UCg5f2-2Ym47GlOepGdoZn7A',
    channelUrl: 'https://www.youtube.com/@KillaKevProd',
    description: 'Legendary HBCU band videographer.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 95,
  },
  {
    name: 'ShowtimeWeb',
    youtubeChannelId: 'UCns2OqWWjNOC7z1L3ib8FVg',
    channelUrl: 'https://www.youtube. com/@ShowtimeWeb',
    description: 'One of the biggest HBCU and show-style marching band channels.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 96,
  },
  {
    name: 'MarchingSport',
    youtubeChannelId: 'UC2ZCPyxCK9HxTL2Qqh1l7eg',
    channelUrl: 'https://www.youtube.com/@MarchingsportHD',
    description: 'Historic HBCU marching band archive and coverage.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 94,
  },
  {
    name: 'A1 Media Bands',
    youtubeChannelId: 'UCcnF4spWEwp369PfQ4JU51w',
    channelUrl: 'https://www.youtube.com/@A1MediaBands',
    description: 'High-quality marching band coverage across high school and college.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 90,
  },
  {
    name: 'Smash Time Productions',
    youtubeChannelId: 'UCQTIn5MfgEkBTbGRghv2MyQ',
    channelUrl: 'https://www.youtube.com/@SmashTimeProductions',
    description: 'Event coverage, band battles, and dance / majorette content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 88,
  },
  {
    name: 'BandTube High Definition',
    youtubeChannelId: 'UCR2Cb125Cm2R7X35LuP9rjg',
    channelUrl: 'https://www.youtube.com/@BandTubeHD',
    description: 'High-definition coverage of marching bands and BOTBs.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 92,
  },
  {
    name: 'JSU Bands',
    youtubeChannelId: 'UCk3tHPULjkpwMVkyNN0Z02Q',
    channelUrl: 'https://www.youtube.com/@JSUBands',
    description: 'Official media for Jackson State\'s Sonic Boom of the South.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 93,
  },
  {
    name: 'Human Jukebox Media',
    youtubeChannelId: 'UC6VM7jSjZ7D4nF1DCJ2w-Gw',
    channelUrl: 'https://www.youtube. com/@su_humanjukebox',
    description: 'Southern University Human Jukebox official media channel.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 93,
  },
  {
    name: 'AAMU Marching Maroon & White',
    youtubeChannelId: 'UCWeUjEMXg_IjJvuk5Dm7-zQ',
    channelUrl: 'https://www.youtube. com/@AAMUBAND',
    description: 'Official channel for Alabama A&M University\'s Marching Maroon & White.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Norfolk State Spartan Legion',
    youtubeChannelId: 'UCOYj1hOj0uZPIWuCrCt2J8Q',
    channelUrl: 'https://www.youtube.com/@nsu_spartanlegion',
    description: 'Official channel for Norfolk State University Spartan Legion.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Lamiks Videos',
    youtubeChannelId: 'UCGmnZVoh86xlvPs-DMQP4QQ',
    channelUrl: 'https://www.youtube. com/@LamiksVideos1',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Band Central',
    youtubeChannelId: 'UC10U5uGD3kHK8R0_LQXp0FA',
    channelUrl: 'https://www.youtube.com/@Bandcentral',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Rickey The Realist',
    youtubeChannelId: 'UCrWQK7EUP35JR7Pn6u_ZJjA',
    channelUrl: 'https://www.youtube.com/@Rickeytherealist1',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Crimson Piper Media',
    youtubeChannelId: 'UC9slanCMZWrSn7UUHRYc7OA',
    channelUrl: 'https://www.youtube.com/@CrimsonPiperMedia',
    description: 'Official media for Tuskegee University Marching Crimson Pipers.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Meet Me on the 50',
    youtubeChannelId: 'UCIAFoCTcC17KmFDEH2C0WpQ',
    channelUrl: 'https://www.youtube.com/@meetmeonthe50',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Marching Ram Show Band',
    youtubeChannelId: 'UCSduiMl4sz1tCnb5X-axBjQ',
    channelUrl: 'https://www.youtube.com/@MarchingRamShowBand1944',
    description: 'Official channel for Albany State University Marching Ram Show Band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'South Carolina State Marching 101',
    youtubeChannelId: 'UC3QPWswazHQniPlp6hV42jA',
    channelUrl: 'https://www.youtube.com/@scsumarching101band',
    description: 'Official channel for South Carolina State University Marching 101.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Mfcool Productions',
    youtubeChannelId: 'UCVqdYfPSULV0EsWm-JrgIsw',
    channelUrl: 'https://www.youtube.com/@MfcoolProductions',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Prairie View Marching Storm',
    youtubeChannelId: 'UC6NQkWeJCQAguQ7xVt8NADQ',
    channelUrl: 'https://www.youtube. com/@MarchingStorm',
    description: 'Official channel for Prairie View A&M University Marching Storm.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'BHN96',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@BHN96',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'BGMM Media',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@BGMMMedia',
    description: 'Official media for North Carolina A&T University Blue and Gold Marching Machine.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'ronconful',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@ronconful',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Marching Hornet Media',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@marchinghornetmedia1931',
    description: 'Official media for Alabama State University Mighty Marching Hornets.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'VSU Marching Band',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@vsuband',
    description: 'Official channel for Virginia State University marching band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'UAPB Bands',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@UAPBBands',
    description: 'Official channel for University of Arkansas at Pine Bluff marching band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'ASMB Media',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@ASMBmedia',
    description: 'Official media for Delaware State University Approaching Storm Marching Band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'BCU Marching Wildcats',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www. youtube.com/@ThePrideofBCUMarchingWildcats',
    description: 'Official channel for Bethune-Cookman University Marching Wildcats.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'The Marching 100',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@themarching100',
    description: 'Official channel for Florida A&M University Marching 100.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 93,
  },
  {
    name: 'FVSU Blue Machine',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@fvsubluemachinemarchingban4392',
    description: 'Official channel for Fort Valley State University Blue Machine.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'P. O.T. S. 1890',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@p.o.t.s. 1890',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Bowie State University Bands',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@bowiestateuniversitybands',
    description: 'Official channel for Bowie State University marching band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Morgan State Bands',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@morganstatebands',
    description: 'Official channel for Morgan State University marching band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Sounds of Dynomite Media',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@SoundsofDynomiteMedia',
    description: 'Official media for Alcorn State University Sounds of Dyn-o-mite.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Sound of Class',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@soundofclass',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Fay State Bands',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@FayStateBands',
    description: 'Official channel for Fayetteville State University marching band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Langston Marching Pride',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@langstonmarchingpride',
    description: 'Official channel for Langston University Marching Pride.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'TSU Aristocrat of Bands',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@tsuaristocratofbands',
    description: 'Official channel for Tennessee State University Aristocrat of Bands.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Hampton University Marching Force',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@HUMarchingForce',
    description: 'Official channel for Hampton University Marching Force.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'Ocean of Soul Media',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@OceanofSoulMedia',
    description: 'Official media for Texas Southern University Ocean of Soul.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'KKrank House',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@KKrankHouseonYT',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
  {
    name: 'Simmons College Marching Band',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@simmonscollegemarchingband',
    description: 'Official channel for Simmons College marching band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 87,
  },
  {
    name: 'GSU World Famed',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube. com/@GSUWorldFamed',
    description: 'Official channel for Grambling State University World Famed Tiger Marching Band.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: true,
    qualityScore: 93,
  },
  {
    name: 'Jeff G Videos',
    youtubeChannelId: '', // TODO: fill via YouTube Data API
    channelUrl: 'https://www.youtube.com/@JeffGVideos',
    description: 'HBCU marching band coverage and content.',
    logoUrl: null,
    thumbnailUrl: null,
    subscriberCount: 0,
    totalVideoCount: 0,
    videosInOurDb: 0,
    isVerified: true,
    isFeatured: false,
    qualityScore: 85,
  },
];


export async function seedCreators(prisma: PrismaClient) {
console.log('Seeding content creators...');
let added = 0;
let updated = 0;

  for (const creator of allCreators) {
const result = await prisma.contentCreator.upsert({
      where: { youtubeChannelId: creator.youtubeChannelId },
      update: creator,
      create: creator,
    });

    if (result.createdAt === result.updatedAt) {
      added++;
      console.log(`✅ Added: ${creator.name}`);
    } else {
      updated++;
      console.log(`🔄 Updated: ${creator.name}`);
    }
  }

  console.log(`\n🎉 Seeding complete!`);
  console.log(`   Added: ${added} creators`);
  console.log(`   Updated: ${updated} creators`);
  console.log(`   Total: ${allCreators.length} creators`);
}

