/**
 * Reads creators-export.json and writes creators-import.sql
 * Run locally: npx tsx scripts/generate-creators-sql.ts
 * Then copy creators-import.sql to the server and run via psql.
 */

import * as fs from 'fs';
import * as path from 'path';

const inputPath = path.join(process.cwd(), 'scripts', 'creators-export.json');
const outputPath = path.join(process.cwd(), 'scripts', 'creators-import.sql');

const creators: any[] = JSON.parse(fs.readFileSync(inputPath, 'utf-8'));

function esc(val: string | null | undefined): string {
  if (val === null || val === undefined) return 'NULL';
  return `'${val.replace(/'/g, "''")}'`;
}

function escNum(val: number | null | undefined): string {
  if (val === null || val === undefined) return '0';
  return String(val);
}

function escBool(val: boolean): string {
  return val ? 'true' : 'false';
}

function escDate(val: string | null | undefined): string {
  if (!val) return 'NULL';
  return `'${val}'`;
}

const lines: string[] = [
  '-- Content creators import',
  '-- Generated by generate-creators-sql.ts',
  '',
];

for (const c of creators) {
  lines.push(
    `INSERT INTO content_creators (` +
    `"id", "name", "youtubeChannelId", "channelUrl", "description", ` +
    `"logoUrl", "thumbnailUrl", "subscriberCount", "totalVideoCount", "videosInOurDb", ` +
    `"isVerified", "isFeatured", "qualityScore", ` +
    `"lastSyncedAt", "firstSyncedAt", "lastFullSync", "createdAt", "updatedAt"` +
    `) VALUES (` +
    `${esc(c.id)}, ${esc(c.name)}, ${esc(c.youtubeChannelId)}, ${esc(c.channelUrl)}, ${esc(c.description)}, ` +
    `${esc(c.logoUrl)}, ${esc(c.thumbnailUrl)}, ${escNum(c.subscriberCount)}, ${escNum(c.totalVideoCount)}, ${escNum(c.videosInOurDb)}, ` +
    `${escBool(c.isVerified)}, ${escBool(c.isFeatured)}, ${escNum(c.qualityScore)}, ` +
    `${escDate(c.lastSyncedAt)}, ${escDate(c.firstSyncedAt)}, ${escDate(c.lastFullSync)}, ${escDate(c.createdAt)}, NOW()` +
    `) ON CONFLICT ("youtubeChannelId") DO UPDATE SET ` +
    `"name" = EXCLUDED."name", "channelUrl" = EXCLUDED."channelUrl", "description" = EXCLUDED."description", ` +
    `"logoUrl" = EXCLUDED."logoUrl", "thumbnailUrl" = EXCLUDED."thumbnailUrl", ` +
    `"subscriberCount" = EXCLUDED."subscriberCount", "totalVideoCount" = EXCLUDED."totalVideoCount", ` +
    `"isVerified" = EXCLUDED."isVerified", "isFeatured" = EXCLUDED."isFeatured", ` +
    `"qualityScore" = EXCLUDED."qualityScore", "updatedAt" = NOW();`
  );
}

fs.writeFileSync(outputPath, lines.join('\n') + '\n', 'utf-8');
console.log(`Wrote ${creators.length} rows to ${outputPath}`);
console.log('\nNext steps on your server:');
console.log('  1. scp scripts/creators-import.sql bandhub@your-server:~/bandhub/');
console.log('  2. docker compose -f docker-compose.prod.yml exec -T postgres \\');
console.log('       psql -U bandhub -d hbcu_band_hub < creators-import.sql');
